### ISSUE TITLE
Error on run Ubuntu

### ISSUE THREAD

**Issue by jlfjunior** [fpanaccia/Wkhtmltopdf.NetCore#41]
System.ComponentModel.Win32Exception (13): Permission denied
   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)
   at Wkhtmltopdf.NetCore.GeneratePdf.GetPDF(String html)
   at BankSlip.Api.Models.Services.BankSlipService.GeneratePdf(IEnumerable`1 bankSlipsModels, Boolean paymentBooklet) in /var/lib/jenkins/workspace/Bankslip.Homol/src/BankSlip.Api/Models/Services/BankSlipService.cs:line 36

**Comment by adriantheking** [comment]
I think its related to [this](https://github.com/fpanaccia/Wkhtmltopdf.NetCore/issues/36#issue-702628853)

**Comment by fpanaccia** [comment]
Hi, sorry for the delay, it's been a rough time for me....have you fixed this? if not, seems like you need to run this 

> chmod 755 PATH_TO_wkhtmltopdf
