### ISSUE TITLE
GetPdfViewInHtml generate "Razor.RuntimeCompilation.CompilationFailedException" error CS1061 on Centos 8

### ISSUE THREAD

**Issue by rpennetta** [fpanaccia/Wkhtmltopdf.NetCore#48]
Like in the object, 
in my asp.net core 3.1 application, normaly when i try to use "GetPdfViewInHtml" it's ok. Whereas if i modify html, in order to use a new field created in datamodel, i obtain this error:

"
_2020-12-29 15:10:08.881 [Error] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:
/Views/FakeView.cshtml(230,45): error CS1061: 'ModuloConsegnaPdfViewModel' non contiene una definizione di 'Responsabile' e non Ã¨ stato trovato alcun metodo di estensione accessibile 'Responsabile' che accetta un primo argomento di tipo 'ModuloConsegnaPdfViewModel'. Probabilmente manca una direttiva using o un riferimento all'assembly.
/Views/FakeView.cshtml(236,33): error CS1061: 'ModuloConsegnaPdfViewModel' non contiene una definizione di 'Responsabile' e non Ã¨ stato trovato alcun metodo di estensione accessibile 'Responsabile' che accetta un primo argomento di tipo 'ModuloConsegnaPdfViewModel'. Probabilmente manca una direttiva using o un riferimento all'assembly.
   at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath)_
"

Thank's

**Comment by rpennetta** [comment]
anybody has never encountered this problem?
