### ISSUE TITLE
Error running under Linux

### ISSUE THREAD

**Issue by lndr-ssantos** [fpanaccia/Wkhtmltopdf.NetCore#49]
When I run the project on Linux I get this error:
```
System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)
   at Wkhtmltopdf.NetCore.GeneratePdf.GetPDF(String html)
```

I've already ran `chmod 755` in Rotativa folder. Works fine locally on my PC running Windows

**Comment by gurustron** [comment]
I bet that you are using .NET 5, so it seems that for now there are not a lot of options here, see:

https://github.com/dotnet/runtime/issues/46469

**Comment by gurustron** [comment]
@fpanaccia I have a fix for this in my private fork, I can backport it here in the evening, will you be able to merge it in the near future, please?

**Comment by lndr-ssantos** [comment]
Thank you @gurustron

**Comment by farukaf** [comment]
Is this problem fixed?
