### ISSUE TITLE
.NET 6 Docker error on GetPDF()

### ISSUE THREAD

**Issue by Ganit20** [fpanaccia/Wkhtmltopdf.NetCore#69]
System.IO.IOException: Pipe is broken.
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Flush()
[10:02:34.268 ERR] [Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] An unhandled exception has occurred while executing the request.
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Wkhtmltopdf.NetCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html)

**Comment by michaelgregson** [comment]
Hi @Ganit20,

I can reproduce this using v3.0.2 when a container is set to have a read only root file system - is this true of your container?

**Comment by Ganit20** [comment]
I forgot to close it, but the reason was a bad html style
